admin_carttype_index:
    path:     /
    defaults: { _controller: "AppBundle:CartType:index" }
    methods:  GET

admin_carttype_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CartType:show" }
    methods:  GET

admin_carttype_new:
    path:     /new
    defaults: { _controller: "AppBundle:CartType:new" }
    methods:  [GET, POST]

admin_carttype_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CartType:edit" }
    methods:  [GET, POST]

admin_carttype_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CartType:delete" }
    methods:  DELETE
