homepage:
    path:     /admin
    defaults: { _controller: "AppBundle:Default:adminIndex" }
    methods:  GET

app_admin_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

app_admin_carttype:
    resource: "@AppBundle/Resources/config/routing/carttype.yml"
    prefix:   /admin/carttype

app_admin_itemtype:
    resource: "@AppBundle/Resources/config/routing/itemtype.yml"
    prefix:   /admin/itemtype