homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  GET

admin_homepage:
    path:     /admin
    defaults: { _controller: "AppBundle:Product:index" }
    methods:  GET

app_admin_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

app_admin_carttype:
    resource: "@AppBundle/Resources/config/routing/carttype.yml"
    prefix:   /admin/carttype

app_admin_producttype:
    resource: "@AppBundle/Resources/config/routing/producttype.yml"
    prefix:   /admin/producttype

app_cart:
    resource: "@AppBundle/Resources/config/routing/cart.yml"
    prefix:   /cart