AppBundle\Entity\CartType:
    type: entity
    table: cart_type
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 40
        name:
            type: string
            length: 255
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
    oneToMany:
        carts:
            targetEntity: Cart
            mappedBy: type
            orphanRemoval: true
            cascade: ["persist","remove"]
    lifecycleCallbacks:
        prePersist: [onPrePersist]
        preUpdate: [onPreUpdate]


