AppBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 40
        name:
            type: string
            length: 255
        price:
            type: string
            length: 40
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
    oneToMany:
        items:
            targetEntity: Item
            mappedBy: product
            orphanRemoval: true
            cascade: ["persist","remove"]
    manyToOne:
        type:
            targetEntity: ProductType
            inversedBy: products
            joinColumn:
                onDelete: CASCADE
                name: type_id
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks:
        prePersist: [onPrePersist]
        preUpdate: [onPreUpdate]
